### ISSUE TITLE
Can't install plugin with 12.1.4

### ISSUE THREAD

**Issue by mpkirby** [codebling/CommunityCase#8]
Perhaps I'm doing something wrong, but I download the communitycase.jar file and attempt to install it into Intellij Idea 12.1.4 (build 129.713) and I get the "not compatible" error message.

I'm assuming they changed the API (again).

Any chance a change coming to fix that?

Thanks,
Mike

**Comment by codebling** [comment]
For sure! I didn't realise that there was another version of 12 coming out. Beware that https://github.com/codebling/CommunityCase/issues/7 will plague 12.1.3+ until it is resolved, and it severely limits the usefulness of the plugin. I'll have a look at 12.1.4, probably only a plugin.xml update of the supported versions is required.

**Comment by mpkirby** [comment]
Note that the issue in intellij is marked as fixed

http://youtrack.jetbrains.com/issue/IDEA-105472#tab=Comments

Fixed in version: 130.360

Which doesn't appear to be version 12.1.4...

Version 13 is 132.xxx, so it looks like it was fixed in that version.

Any chance there is a version that works with the EIP version of 13.x?

Mike

**Comment by codebling** [comment]
There should be another version tagged in the "Fixed in build" field. If you look above at the "Fixed in versions", it shows 13 and 12.1.2. 

If you have a look at my comments on that issue, you'll see that my problem was WITH the fix that was made...or so I thought. I finally had a chance on Sunday night to make a little sample program to analyse whether arguments were being correctly passed or not, and they are. I think part of the confusion lay in the fact that quotation marks are NOT needed when passing parameters containing spaces when invoking through GeneralCommandLine. I've fixed this in the CommunityCase code, and though I only briefly had a chance to try it out, it seemed to work. 

Sorry for the HUGE delay, glad to hear you're still interested. I'll push the changes right now and you can try it out !

**Comment by codebling** [comment]
fixed 05f7747ccb

**Comment by codebling** [comment]
You can use the IntelliJ "Install plugin from disk..." option from Plugins in IDE Settings and point it to [this file](https://github.com/codebling/CommunityCase/blob/12.1.4-129.713/CommunityCase.jar?raw=true)

**Comment by mpkirby** [comment]
I downloaded the jar file, and then from settings->install from disk, setlect the .jar file.

I get a " Fail to load plugin descriptor from file CommunityCase.jar"

I'm running 12.1.4, 129-713

Mike

**Comment by codebling** [comment]
Looking at it right now..

**Comment by codebling** [comment]
Ah.. Sorry, the link needed ?raw=true, otherwise it shows you a web page with the contents of the file. I fixed the link above, so you should be able to use "Save As.." as you were doing before.

**Comment by mpkirby** [comment]
I got it to load.  Seems to check files out okay.  

I did a lshistory, and saw this:

4:26:55 PM Problems while loading file history: cleartool: Error: Unrecognized option "-fmt"
           Usage: get -to dest-pname pname
           cleartool: Error: Unrecognized option "-fmt"
           Usage: get -to dest-pname pname

Note it is showing me the history, so I'm not sure why I'm getting the error.

-fmt is an argument to lshistory, and given the error, it is almost like the command:

cleartool lshistory -ftm ....

is really 

cleartool -fmt ...

(the lshistory is getting dropped??)

**Comment by codebling** [comment]
It's issuing the -fmt argument after a "cleartool get" command. I'll have to see why. 

You can see every command being issued by opening the "Version Control" tool window and clicking on the "Console" tab. Are you still using the plugin?

**Comment by codebling** [comment]
Issue #3 already exists for that problem. Fixed and closed.
